source 'https://rubygems.org'

gem 'aws-sdk-ec2', '~> 1.233', '>= 1.233.0'
gem 'aws-sdk-autoscaling', '~> 1.59', '>= 1.59.0'
gem 'aws-sdk-elasticloadbalancing', '~> 1.31', '>= 1.31.0'
gem 'aws-sdk-elasticloadbalancingv2', '~> 1.61', '>= 1.61.0'

gem 'rexml',                          '~> 3.2.5'
gem 'bosh_common', '1.3262.24.0'
gem 'bosh_cpi'

group :development, :test do
  gem 'aws-sdk-iam', '~> 1.52', '>= 1.52.0'
  gem 'pry-byebug',  '~>3.4'
  gem 'rspec',       '~>3.5'
  gem 'rake',        '~>12.3'
  gem 'webmock'
end
